apiVersion: v2
name: is-it-up-tho
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: prometheus-blackbox-exporter
    version: "8.8.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: blackboxExporter.enabled

  - name: alloy
    version: "0.9.2"
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled

  - name: grafana-operator
    version: "5.16.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafanaOperator.enabled

  - name: mimir-distributed
    version: "5.5.0"
    repository: https://grafana.github.io/helm-charts
    condition: mimir.enabled