apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.servicename" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "common.prometheusPort" . }}
      targetPort: {{ include "common.prometheusPort" . }}
      protocol: TCP
      name: web
  selector:
    app: {{ include "common.name" . }}
    release: {{ .Release.Name }}
---
{{- if .Values.probe.blackbox.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.servicename" . }}-blackbox
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    component: blackbox-exporter
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9115
      targetPort: 9115
      protocol: TCP
      name: http
  selector:
    app: {{ include "common.name" . }}
    component: blackbox-exporter
{{- end }}